/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IGU;
import Logica.*;
import PlaceHolder.TextPrompt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juand
 */
public class empresaTelecomunicacion extends javax.swing.JFrame {

    /**
     * Creates new form empresaTelecomunicacion
     */
    public empresaTelecomunicacion() {
        initComponents();
        TextPrompt tp = new TextPrompt("dd/mm/aaaa", VjTextFieldFIO);
        tp = new TextPrompt("Color, Tipo de caja, Informacion extra", VjTextAreaDescripcion);
        tp = new TextPrompt("dd/mm/aaaa", CjTextFieldFechaNacimiento);
        tp = new TextPrompt("Masculino/Femenino/Otro", CjTextFieldGenero);
        tp = new TextPrompt("Mañana/Tarde/Noche", CjTextFieldTurno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        VjTextFieldFIO = new javax.swing.JTextField();
        VjTextFieldModelo = new javax.swing.JTextField();
        VjTextFieldMarca = new javax.swing.JTextField();
        VjTextFieldTipo = new javax.swing.JTextField();
        VjTextFieldPlaca = new javax.swing.JTextField();
        VjTextFieldCodVehiculo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        VjTextAreaDescripcion = new javax.swing.JTextArea();
        VjButtonGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        AEjTextFieldFIO = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AEjTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        AEjTextFieldModelo = new javax.swing.JTextField();
        AEjTextFieldMarca = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        AEjTextFieldTipo = new javax.swing.JTextField();
        AEjTextFieldPlaca = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        AEjTextFieldCodVehiculoV = new javax.swing.JTextField();
        AEjButtonConsultarV = new javax.swing.JButton();
        AEjButtonEliminarV = new javax.swing.JButton();
        AEjButtonActualizarV = new javax.swing.JButton();
        AEjLabelEstadoAsignacion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CjButtonGuardar = new javax.swing.JButton();
        CjTextFieldCodVehiculo = new javax.swing.JTextField();
        CjTextFieldEstadoCivil = new javax.swing.JTextField();
        CjTextFieldBarrio = new javax.swing.JTextField();
        CjTextFieldDireccion = new javax.swing.JTextField();
        CjTextFieldCiudadResidencia = new javax.swing.JTextField();
        CjTextFieldTurno = new javax.swing.JTextField();
        CjTextFieldCatLicencia = new javax.swing.JTextField();
        CjTextFieldNumLicencia = new javax.swing.JTextField();
        CjTextFieldCorreo = new javax.swing.JTextField();
        CjTextFieldFechaNacimiento = new javax.swing.JTextField();
        CjTextFieldCelular = new javax.swing.JTextField();
        CjTextFieldTelefono = new javax.swing.JTextField();
        CjTextFieldGenero = new javax.swing.JTextField();
        CjTextFieldApellido = new javax.swing.JTextField();
        CjTextFieldNombre = new javax.swing.JTextField();
        CjTextFieldId = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        AEjTextFieldCodVehiculo = new javax.swing.JTextField();
        AEjTextFieldEstadoCivil = new javax.swing.JTextField();
        AEjTextFieldBarrio = new javax.swing.JTextField();
        AEjTextFieldDireccion = new javax.swing.JTextField();
        AEjTextFieldCiudadResidencia = new javax.swing.JTextField();
        AEjTextFieldTurno = new javax.swing.JTextField();
        AEjTextFieldCatLicencia = new javax.swing.JTextField();
        AEjTextFieldNumLicencia = new javax.swing.JTextField();
        AEjTextFieldCorreo = new javax.swing.JTextField();
        AEjTextFieldFechaNacimiento = new javax.swing.JTextField();
        AEjTextFieldCelular = new javax.swing.JTextField();
        AEjTextFieldTelefono = new javax.swing.JTextField();
        AEjTextFieldGenero = new javax.swing.JTextField();
        AEjTextFieldApellido = new javax.swing.JTextField();
        AEjTextFieldNombre = new javax.swing.JTextField();
        AEjTextFieldId = new javax.swing.JTextField();
        AEjButtonConsultarC = new javax.swing.JButton();
        AEjButtonActualizarC = new javax.swing.JButton();
        AEjButtonEliminarC = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(475, 700));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(475, 800));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Codigo del Vehiculo");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Placa");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Tipo");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Marca");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Modelo");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Descripcion");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Fecha de Inicio de Operacion");

        VjTextFieldFIO.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextFieldModelo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextFieldMarca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextFieldTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextFieldPlaca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextFieldCodVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        VjTextAreaDescripcion.setColumns(20);
        VjTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(VjTextAreaDescripcion);

        VjButtonGuardar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        VjButtonGuardar.setText("Guardar");
        VjButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VjButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VjTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VjTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VjTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(116, 116, 116)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VjTextFieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(VjTextFieldFIO, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(VjButtonGuardar)
                .addGap(193, 193, 193))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(VjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(VjTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(VjTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(VjTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(VjTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(VjTextFieldFIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(VjButtonGuardar)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Ingresar", jPanel3);

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel41.setText("Estado de Asignacion");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel42.setText("Fecha de Inicio de Operacion");

        AEjTextFieldFIO.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextAreaDescripcion.setColumns(20);
        AEjTextAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(AEjTextAreaDescripcion);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel43.setText("Descripcion");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel44.setText("Modelo");

        AEjTextFieldModelo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldMarca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel45.setText("Marca");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel46.setText("Tipo");

        AEjTextFieldTipo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldPlaca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel47.setText("Placa");

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel48.setText("Codigo del Vehiculo");

        AEjTextFieldCodVehiculoV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjButtonConsultarV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonConsultarV.setText("Consultar");
        AEjButtonConsultarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonConsultarVActionPerformed(evt);
            }
        });

        AEjButtonEliminarV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonEliminarV.setText("Eliminar");
        AEjButtonEliminarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonEliminarVActionPerformed(evt);
            }
        });

        AEjButtonActualizarV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonActualizarV.setText("Actualizar");
        AEjButtonActualizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonActualizarVActionPerformed(evt);
            }
        });

        AEjLabelEstadoAsignacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjLabelEstadoAsignacion.setMaximumSize(new java.awt.Dimension(250, 20));
        AEjLabelEstadoAsignacion.setMinimumSize(new java.awt.Dimension(233, 17));
        AEjLabelEstadoAsignacion.setPreferredSize(new java.awt.Dimension(233, 17));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AEjTextFieldCodVehiculoV, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AEjTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AEjTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AEjTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(116, 116, 116)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AEjTextFieldModelo)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addGap(63, 63, 63)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AEjTextFieldFIO)
                                    .addComponent(AEjLabelEstadoAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(AEjButtonConsultarV))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(AEjButtonActualizarV)
                        .addGap(18, 18, 18)
                        .addComponent(AEjButtonEliminarV)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(AEjTextFieldCodVehiculoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AEjButtonConsultarV)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(AEjTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(AEjTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(AEjTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(AEjTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(AEjTextFieldFIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(AEjLabelEstadoAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEjButtonActualizarV)
                    .addComponent(AEjButtonEliminarV))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Actualizar/Eliminar", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Consultas", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Vehiculo", jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Identificacion");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Genero");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Celular");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Correo Electronico");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Numero de Licencia");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Categoria de Licencia");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Turno");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Ciudad de Residencia");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Direccion");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Barrio");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Estado Civil");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Codigo del Vehiculo Asignado");

        CjButtonGuardar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CjButtonGuardar.setText("Guardar");
        CjButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CjButtonGuardarActionPerformed(evt);
            }
        });

        CjTextFieldCodVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldEstadoCivil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldBarrio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldCiudadResidencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldTurno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldCatLicencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldNumLicencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldFechaNacimiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldCelular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CjTextFieldId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CjTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldNumLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldCatLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldCiudadResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(CjButtonGuardar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CjTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CjTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CjTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CjTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CjTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CjTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CjTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CjTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CjTextFieldNumLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CjTextFieldCatLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CjTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CjTextFieldCiudadResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CjTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CjTextFieldBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CjTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(CjButtonGuardar)
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("Ingresar", jPanel6);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Nombre");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Identificacion");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Apellido");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Genero");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("Telefono");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Celular");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("Fecha de Nacimiento");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Correo Electronico");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setText("Numero de Licencia");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setText("Categoria de Licencia");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setText("Turno");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setText("Ciudad de Residencia");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("Direccion");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setText("Barrio");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setText("Estado Civil");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("Codigo del Vehiculo Asignado");

        AEjTextFieldCodVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldEstadoCivil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldBarrio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldCiudadResidencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldTurno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldCatLicencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldNumLicencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldFechaNacimiento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldCelular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjTextFieldId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AEjButtonConsultarC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonConsultarC.setText("Consultar");
        AEjButtonConsultarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonConsultarCActionPerformed(evt);
            }
        });

        AEjButtonActualizarC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonActualizarC.setText("Actualizar");
        AEjButtonActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonActualizarCActionPerformed(evt);
            }
        });

        AEjButtonEliminarC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AEjButtonEliminarC.setText("Eliminar");
        AEjButtonEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEjButtonEliminarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AEjTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldNumLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldCatLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldCiudadResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AEjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(AEjButtonConsultarC))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(AEjButtonActualizarC)
                        .addGap(18, 18, 18)
                        .addComponent(AEjButtonEliminarC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(AEjTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(AEjButtonConsultarC)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(AEjTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(AEjTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(AEjTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(AEjTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(AEjTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(AEjTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(AEjTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(AEjTextFieldNumLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(AEjTextFieldCatLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(AEjTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(AEjTextFieldCiudadResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(AEjTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(AEjTextFieldBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(AEjTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(AEjTextFieldCodVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AEjButtonActualizarC)
                    .addComponent(AEjButtonEliminarC))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Actualizar/Eliminar", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Consultas", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Conductor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VjButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VjButtonGuardarActionPerformed
        try {
            vehiculo veh = new vehiculo();
            
            veh.setCodigoVehiculo(Long.parseLong(VjTextFieldCodVehiculo.getText()));
            veh.setPlaca(VjTextFieldPlaca.getText());
            veh.setTipo(VjTextFieldTipo.getText());
            veh.setMarca(VjTextFieldMarca.getText());
            veh.setModelo(VjTextFieldModelo.getText());
            veh.setDescripcion(VjTextAreaDescripcion.getText());
            veh.setFechaInicioOperacion(VjTextFieldFIO.getText());
            
            boolean guardarOk = veh.guardarVehiculo();
            
            if (guardarOk) {
                VjTextFieldCodVehiculo.setText("");
                VjTextFieldPlaca.setText("");
                VjTextFieldTipo.setText("");
                VjTextFieldMarca.setText("");
                VjTextFieldModelo.setText("");
                VjTextAreaDescripcion.setText("");
                VjTextFieldFIO.setText("");
                
                JOptionPane.showMessageDialog(rootPane, "Este Vehiculo ha sido Guardado Correctamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un error y no se ha podido guardar este Vehiculo en el sistema");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Se ha presentado un error " + e.getMessage());
        }
    }//GEN-LAST:event_VjButtonGuardarActionPerformed

    private void CjButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CjButtonGuardarActionPerformed
        try {
            conductor con = new conductor();
            
            con.setId(Long.parseLong(CjTextFieldId.getText()));
            con.setNombre(CjTextFieldNombre.getText());
            con.setApellido(CjTextFieldApellido.getText());
            con.setGenero(CjTextFieldGenero.getText());
            con.setTelefono(CjTextFieldTelefono.getText());
            con.setCelular(CjTextFieldCelular.getText());
            con.setFechaNacimiento(CjTextFieldFechaNacimiento.getText());
            con.setCorreo(CjTextFieldCorreo.getText());
            con.setNumLicencia(CjTextFieldNumLicencia.getText());
            con.setCategoriaLicencia(CjTextFieldCatLicencia.getText());
            con.setTurno(CjTextFieldTurno.getText());
            con.setCiudadResidencia(CjTextFieldCiudadResidencia.getText());
            con.setDireccion(CjTextFieldDireccion.getText());
            con.setBarrio(CjTextFieldBarrio.getText());
            con.setEstadoCivil(CjTextFieldEstadoCivil.getText());
            con.setCodigoVehiculo(Long.parseLong(CjTextFieldCodVehiculo.getText()));
            
            
            boolean guardarOk = con.guardarConductor();
            
            if (guardarOk) {
                CjTextFieldId.setText("");
                CjTextFieldNombre.setText("");
                CjTextFieldApellido.setText("");
                CjTextFieldGenero.setText("");
                CjTextFieldTelefono.setText("");
                CjTextFieldCelular.setText("");
                CjTextFieldFechaNacimiento.setText("");
                CjTextFieldCorreo.setText("");
                CjTextFieldNumLicencia.setText("");
                CjTextFieldCatLicencia.setText("");
                CjTextFieldTurno.setText("");
                CjTextFieldCiudadResidencia.setText("");
                CjTextFieldDireccion.setText("");
                CjTextFieldBarrio.setText("");
                CjTextFieldEstadoCivil.setText("");
                CjTextFieldCodVehiculo.setText("");
                
                JOptionPane.showMessageDialog(rootPane, "Este Conductor ha sido Guardado Correctamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un error y no se ha podido guardar este Conductor en el sistema");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Se ha presentado un error " + e.getMessage());
        }
    }//GEN-LAST:event_CjButtonGuardarActionPerformed

    private void AEjButtonConsultarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonConsultarCActionPerformed
        try {
            conductor con = new conductor();
            boolean consultaOk = con.consultarConductorId(Long.parseLong(AEjTextFieldId.getText()));
            if (consultaOk) {
                AEjTextFieldId.setEnabled(false);
                AEjTextFieldNombre.setText(con.getNombre());
                AEjTextFieldApellido.setText(con.getApellido());
                AEjTextFieldGenero.setText(con.getGenero());
                AEjTextFieldTelefono.setText(con.getTelefono());
                AEjTextFieldCelular.setText(con.getCelular());
                AEjTextFieldFechaNacimiento.setText(con.getFecahaNacimiento());
                AEjTextFieldCorreo.setText(con.getCorreo());
                AEjTextFieldNumLicencia.setText(con.getNumLicencia());
                AEjTextFieldCatLicencia.setText(con.getCategoriaLicencia());
                AEjTextFieldTurno.setText(con.getTurno());
                AEjTextFieldCiudadResidencia.setText(con.getCiudadResidencia());
                AEjTextFieldDireccion.setText(con.getDireccion());
                AEjTextFieldBarrio.setText(con.getBarrio());
                AEjTextFieldEstadoCivil.setText(con.getEstadoCivil());
                AEjTextFieldCodVehiculo.setText(String.valueOf(con.getCodigoVehiculo()));
                
                JOptionPane.showMessageDialog(rootPane, "Consulta realizada con exito");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningun Conductor con esta identificación, Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonConsultarCActionPerformed

    private void AEjButtonActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonActualizarCActionPerformed
        try {
            conductor con = new conductor();
            
            con.setId(Long.parseLong(AEjTextFieldId.getText()));
            con.setNombre(AEjTextFieldNombre.getText());
            con.setApellido(AEjTextFieldApellido.getText());
            con.setGenero(AEjTextFieldGenero.getText());
            con.setTelefono(AEjTextFieldTelefono.getText());
            con.setCelular(AEjTextFieldCelular.getText());
            con.setFechaNacimiento(AEjTextFieldFechaNacimiento.getText());
            con.setCorreo(AEjTextFieldCorreo.getText());
            con.setNumLicencia(AEjTextFieldNumLicencia.getText());
            con.setCategoriaLicencia(AEjTextFieldCatLicencia.getText());
            con.setTurno(AEjTextFieldTurno.getText());
            con.setCiudadResidencia(AEjTextFieldCiudadResidencia.getText());
            con.setDireccion(AEjTextFieldDireccion.getText());
            con.setBarrio(AEjTextFieldBarrio.getText());
            con.setEstadoCivil(AEjTextFieldEstadoCivil.getText());
            con.setCodigoVehiculo(Long.parseLong(AEjTextFieldCodVehiculo.getText()));
            boolean actualizarOk = con.actualizarConductor();
            
            if (actualizarOk) {
                AEjTextFieldId.setText("");
                AEjTextFieldId.setEnabled(true);
                AEjTextFieldNombre.setText("");
                AEjTextFieldApellido.setText("");
                AEjTextFieldGenero.setText("");
                AEjTextFieldTelefono.setText("");
                AEjTextFieldCelular.setText("");
                AEjTextFieldFechaNacimiento.setText("");
                AEjTextFieldCorreo.setText("");
                AEjTextFieldNumLicencia.setText("");
                AEjTextFieldCatLicencia.setText("");
                AEjTextFieldTurno.setText("");
                AEjTextFieldCiudadResidencia.setText("");
                AEjTextFieldDireccion.setText("");
                AEjTextFieldBarrio.setText("");
                AEjTextFieldEstadoCivil.setText("");
                AEjTextFieldCodVehiculo.setText("");

                JOptionPane.showMessageDialog(rootPane, "Este Conductor Fue Actualizado Correctamente");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un Error y No se ha podido Actualizar este Conductor. Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonActualizarCActionPerformed

    private void AEjButtonConsultarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonConsultarVActionPerformed
        try {
            vehiculo veh = new vehiculo();
            boolean consultaOk = veh.consultarVehiculoCodVehiculo(Long.parseLong(AEjTextFieldCodVehiculoV.getText()));
            if (consultaOk) {
                AEjTextFieldCodVehiculoV.setEnabled(false);
                AEjTextFieldPlaca.setText(veh.getPlaca());
                AEjTextFieldTipo.setText(veh.getTipo());
                AEjTextFieldMarca.setText(veh.getMarca());
                AEjTextFieldModelo.setText(veh.getModelo());
                AEjTextAreaDescripcion.setText(veh.getDescripcion());
                AEjTextFieldFIO.setText(veh.getFechaInicioOperacion());
                AEjLabelEstadoAsignacion.setText(String.valueOf(veh.getEstadoAsignacion()));
                
                JOptionPane.showMessageDialog(rootPane, "Consulta realizada con exito");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se ha encontrado ningun Vehiculo con esta identificación, Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonConsultarVActionPerformed

    private void AEjButtonActualizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonActualizarVActionPerformed
        try {
            vehiculo veh = new vehiculo();
            
            veh.setCodigoVehiculo(Long.parseLong(AEjTextFieldCodVehiculoV.getText()));
            veh.setPlaca(AEjTextFieldPlaca.getText());
            veh.setTipo(AEjTextFieldTipo.getText());
            veh.setMarca(AEjTextFieldMarca.getText());
            veh.setModelo(AEjTextFieldModelo.getText());
            veh.setDescripcion(AEjTextAreaDescripcion.getText());
            veh.setFechaInicioOperacion(AEjTextFieldFIO.getText());
            boolean actualizarOk = veh.actualizarVehiculo();
            
            if (actualizarOk) {
                AEjTextFieldCodVehiculoV.setText("");
                AEjTextFieldCodVehiculoV.setEnabled(true);
                AEjTextFieldPlaca.setText("");
                AEjTextFieldTipo.setText("");
                AEjTextFieldMarca.setText("");
                AEjTextFieldModelo.setText("");
                AEjTextAreaDescripcion.setText("");
                AEjTextFieldFIO.setText("");
                AEjLabelEstadoAsignacion.setText("");

                JOptionPane.showMessageDialog(rootPane, "Este Vehiculo Fue Actualizado Correctamente");
            }else {
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un Error y No se ha podido Actualizar este Vehiculo. Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonActualizarVActionPerformed

    private void AEjButtonEliminarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonEliminarVActionPerformed
        try {
            vehiculo veh = new vehiculo();
            boolean eliminarOk = veh.eliminarVehiculo(Long.parseLong(AEjTextFieldCodVehiculoV.getText()));
            if (eliminarOk==true) {
                AEjTextFieldCodVehiculoV.setText("");
                AEjTextFieldCodVehiculoV.setEnabled(true);
                AEjTextFieldPlaca.setText("");
                AEjTextFieldTipo.setText("");
                AEjTextFieldMarca.setText("");
                AEjTextFieldModelo.setText("");
                AEjTextAreaDescripcion.setText("");
                AEjTextFieldFIO.setText("");
                AEjLabelEstadoAsignacion.setText("");
                JOptionPane.showMessageDialog(rootPane, "Este Vehiculo Fue Eliminado Correctamente");
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un Error y No se ha podido Eliminar este Vehiculo. Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonEliminarVActionPerformed

    private void AEjButtonEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEjButtonEliminarCActionPerformed
        try {
            conductor con = new conductor();
            boolean eliminarOk = con.eliminarConductor(Long.parseLong(AEjTextFieldId.getText()));
            if (eliminarOk==true) {
                AEjTextFieldId.setText("");
                AEjTextFieldId.setEnabled(true);
                AEjTextFieldNombre.setText("");
                AEjTextFieldApellido.setText("");
                AEjTextFieldGenero.setText("");
                AEjTextFieldTelefono.setText("");
                AEjTextFieldCelular.setText("");
                AEjTextFieldFechaNacimiento.setText("");
                AEjTextFieldCorreo.setText("");
                AEjTextFieldNumLicencia.setText("");
                AEjTextFieldCatLicencia.setText("");
                AEjTextFieldTurno.setText("");
                AEjTextFieldCiudadResidencia.setText("");
                AEjTextFieldDireccion.setText("");
                AEjTextFieldBarrio.setText("");
                AEjTextFieldEstadoCivil.setText("");
                AEjTextFieldCodVehiculo.setText("");
                JOptionPane.showMessageDialog(rootPane, "Este Conductor Fue Eliminado Correctamente");
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Se ha presentado un Error y No se ha podido Eliminar este Conductor. Verifique e intente nuevamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Se ha presentado un Error. " + e.getMessage());
        }
    }//GEN-LAST:event_AEjButtonEliminarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empresaTelecomunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empresaTelecomunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empresaTelecomunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empresaTelecomunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empresaTelecomunicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AEjButtonActualizarC;
    private javax.swing.JButton AEjButtonActualizarV;
    private javax.swing.JButton AEjButtonConsultarC;
    private javax.swing.JButton AEjButtonConsultarV;
    private javax.swing.JButton AEjButtonEliminarC;
    private javax.swing.JButton AEjButtonEliminarV;
    private javax.swing.JLabel AEjLabelEstadoAsignacion;
    private javax.swing.JTextArea AEjTextAreaDescripcion;
    private javax.swing.JTextField AEjTextFieldApellido;
    private javax.swing.JTextField AEjTextFieldBarrio;
    private javax.swing.JTextField AEjTextFieldCatLicencia;
    private javax.swing.JTextField AEjTextFieldCelular;
    private javax.swing.JTextField AEjTextFieldCiudadResidencia;
    private javax.swing.JTextField AEjTextFieldCodVehiculo;
    private javax.swing.JTextField AEjTextFieldCodVehiculoV;
    private javax.swing.JTextField AEjTextFieldCorreo;
    private javax.swing.JTextField AEjTextFieldDireccion;
    private javax.swing.JTextField AEjTextFieldEstadoCivil;
    private javax.swing.JTextField AEjTextFieldFIO;
    private javax.swing.JTextField AEjTextFieldFechaNacimiento;
    private javax.swing.JTextField AEjTextFieldGenero;
    private javax.swing.JTextField AEjTextFieldId;
    private javax.swing.JTextField AEjTextFieldMarca;
    private javax.swing.JTextField AEjTextFieldModelo;
    private javax.swing.JTextField AEjTextFieldNombre;
    private javax.swing.JTextField AEjTextFieldNumLicencia;
    private javax.swing.JTextField AEjTextFieldPlaca;
    private javax.swing.JTextField AEjTextFieldTelefono;
    private javax.swing.JTextField AEjTextFieldTipo;
    private javax.swing.JTextField AEjTextFieldTurno;
    private javax.swing.JButton CjButtonGuardar;
    private javax.swing.JTextField CjTextFieldApellido;
    private javax.swing.JTextField CjTextFieldBarrio;
    private javax.swing.JTextField CjTextFieldCatLicencia;
    private javax.swing.JTextField CjTextFieldCelular;
    private javax.swing.JTextField CjTextFieldCiudadResidencia;
    private javax.swing.JTextField CjTextFieldCodVehiculo;
    private javax.swing.JTextField CjTextFieldCorreo;
    private javax.swing.JTextField CjTextFieldDireccion;
    private javax.swing.JTextField CjTextFieldEstadoCivil;
    private javax.swing.JTextField CjTextFieldFechaNacimiento;
    private javax.swing.JTextField CjTextFieldGenero;
    private javax.swing.JTextField CjTextFieldId;
    private javax.swing.JTextField CjTextFieldNombre;
    private javax.swing.JTextField CjTextFieldNumLicencia;
    private javax.swing.JTextField CjTextFieldTelefono;
    private javax.swing.JTextField CjTextFieldTurno;
    private javax.swing.JButton VjButtonGuardar;
    private javax.swing.JTextArea VjTextAreaDescripcion;
    private javax.swing.JTextField VjTextFieldCodVehiculo;
    private javax.swing.JTextField VjTextFieldFIO;
    private javax.swing.JTextField VjTextFieldMarca;
    private javax.swing.JTextField VjTextFieldModelo;
    private javax.swing.JTextField VjTextFieldPlaca;
    private javax.swing.JTextField VjTextFieldTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
